# Generated by Django 2.2.7 on 2019-11-20 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Undefined', max_length=64)),
                ('name', models.CharField(default='Undefined', max_length=64)),
            ],
            options={
                'db_table': 'budcodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bumon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined', max_length=32)),
                ('budget_manager', models.CharField(default='Undefined', max_length=32)),
            ],
            options={
                'db_table': 'bumon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DepCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Undefined', max_length=32)),
                ('name', models.CharField(default='Undefined', max_length=32)),
            ],
            options={
                'db_table': 'depcodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Undefined', max_length=16)),
            ],
            options={
                'db_table': 'order_status_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='syozoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='Undefined', max_length=16)),
            ],
            options={
                'db_table': 'syozoku_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.CharField(default='&nbsp;', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(default='&nbsp;', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='syozoku',
            field=models.CharField(default='nobody', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default='nobody', max_length=32),
        ),
        migrations.CreateModel(
            name='ProCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Undefined', max_length=32)),
                ('name', models.CharField(default='Undefined', max_length=32)),
                ('syozoku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.syozoku')),
            ],
            options={
                'db_table': 'procodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdffile', models.FileField(blank=True, null=True, upload_to='pdffiles/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDFファイル')),
                ('nendo', models.CharField(default='', max_length=32, verbose_name='年度')),
                ('bango', models.IntegerField(verbose_name='整理番号')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='依頼(発注)年月日')),
                ('orderer', models.CharField(max_length=32, verbose_name='依頼(発注)者')),
                ('phone', models.CharField(max_length=32, verbose_name='連絡先')),
                ('delivery_place', models.CharField(max_length=32, verbose_name='納品場所')),
                ('item_name', models.TextField(verbose_name='品名')),
                ('kikaku', models.TextField(max_length=1024, verbose_name='規格')),
                ('suuryou', models.PositiveIntegerField(verbose_name='数量')),
                ('tanka', models.PositiveIntegerField(verbose_name='単価')),
                ('kingaku', models.PositiveIntegerField(verbose_name='金額')),
                ('suppliers', models.CharField(max_length=64, verbose_name='取引先名')),
                ('invoice_number', models.CharField(max_length=32, verbose_name='請求書番号')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('budget_subject_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.BudCode', verbose_name='予算科目')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Bumon', verbose_name='部門')),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.DepCode', verbose_name='部署')),
                ('kingaku_zei', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kingaku_zei', to='system.tax', verbose_name='金額(税込/税抜)')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.order_status', verbose_name='発注状況')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.ProCode', verbose_name='プロジェクト')),
                ('tanka_zei', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanka_zei', to='system.tax', verbose_name='単価(税込/税抜)')),
                ('tanni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.unit', verbose_name='単位')),
            ],
            options={
                'verbose_name': '発注',
                'verbose_name_plural': '発注リスト',
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='depcode',
            name='syozoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.syozoku'),
        ),
        migrations.AddField(
            model_name='bumon',
            name='syozoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.syozoku'),
        ),
        migrations.AddField(
            model_name='budcode',
            name='syozoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.syozoku'),
        ),
    ]
