# Generated by Django 2.2.7 on 2019-11-26 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191120_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='syozoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.syozoku'),
        ),
    ]
