# Generated by Django 2.2.7 on 2019-11-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191126_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='syozoku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='system.syozoku'),
        ),
    ]
