# Generated by Django 2.2.7 on 2019-11-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20191126_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='budget_subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.BudCode', verbose_name='予算科目名,コード'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='納品場所'),
        ),
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Bumon', verbose_name='部門<予算責任者>'),
        ),
        migrations.AlterField(
            model_name='order',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.DepCode', verbose_name='部署名,コード'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='請求書番号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.ProCode', verbose_name='プロジェクト名,コード'),
        ),
        migrations.AlterField(
            model_name='order',
            name='suppliers',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='取引先名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tanka',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='syozoku',
            name='desc',
            field=models.CharField(default='Undefined', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, default='nobody', max_length=32, null=True),
        ),
    ]
