# Generated by Django 2.2.8 on 2019-12-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20191129_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budcode',
            options={'managed': True, 'verbose_name': '予算科目コード', 'verbose_name_plural': '予算科目コード'},
        ),
        migrations.AlterModelOptions(
            name='bumon',
            options={'managed': True, 'verbose_name': '部門', 'verbose_name_plural': '部門'},
        ),
        migrations.AlterModelOptions(
            name='depcode',
            options={'managed': True, 'verbose_name': '部署コード', 'verbose_name_plural': '部署コード'},
        ),
        migrations.AlterModelOptions(
            name='order_status',
            options={'managed': True, 'verbose_name': '発注状況', 'verbose_name_plural': '発注状況'},
        ),
        migrations.AlterModelOptions(
            name='procode',
            options={'managed': True, 'verbose_name': 'プロジェクトコード', 'verbose_name_plural': 'プロジェクトコード'},
        ),
        migrations.AlterModelOptions(
            name='syozoku',
            options={'managed': True, 'verbose_name': '所属', 'verbose_name_plural': '所属'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'managed': True, 'verbose_name': '税', 'verbose_name_plural': '税'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'managed': True, 'verbose_name': '単位', 'verbose_name_plural': '単位'},
        ),
        migrations.AddField(
            model_name='order',
            name='syozoku',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='system.syozoku'),
            preserve_default=False,
        ),
    ]
