# Generated by Django 2.2.8 on 2020-03-10 02:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20191223_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bango',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name='整理番号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kingaku',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='order',
            name='suuryou',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='syozoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.syozoku', verbose_name='所属ID(変更不可)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tanka',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='included',
            field=models.CharField(default='nobody', max_length=12),
        ),
        migrations.AlterField(
            model_name='unit',
            name='classifier',
            field=models.CharField(default='nobody', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='syozoku',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='system.syozoku'),
        ),
    ]
