# Generated by Django 2.2.8 on 2020-03-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200310_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kikaku',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='規格'),
        ),
    ]
