# Generated by Django 2.2.8 on 2020-03-17 03:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20200310_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budcode',
            name='syozoku',
        ),
        migrations.RemoveField(
            model_name='depcode',
            name='syozoku',
        ),
        migrations.RemoveField(
            model_name='procode',
            name='syozoku',
        ),
        migrations.AddField(
            model_name='syozoku',
            name='budcode',
            field=models.ManyToManyField(related_name='syozoku', to='system.BudCode'),
        ),
        migrations.AddField(
            model_name='syozoku',
            name='depcode',
            field=models.ManyToManyField(related_name='syozoku', to='system.DepCode'),
        ),
        migrations.AddField(
            model_name='syozoku',
            name='project',
            field=models.ManyToManyField(related_name='syozoku', to='system.ProCode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kingaku',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name=' 金額'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kingaku_zei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kingaku_zei', to='system.tax', verbose_name=' 金額(税込/税抜)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='依頼(発注) 年月日'),
        ),
        migrations.AlterField(
            model_name='order',
            name='suuryou',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name=' 数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='syozoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.syozoku', verbose_name=' 所属ID(変更不可)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tanka_zei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanka_zei', to='system.tax', verbose_name='単 価(税込/税抜)'),
        ),
    ]
